# NumPy

NumPy (Numerical Python) is an open-source Python library used for numerical computing.

It provides support for:

+ Multi-dimensional arrays (ndarrays) for storing and manipulating large datasets.
+ Mathematical functions for operations like linear algebra, statistics, and Fourier transforms.
+ High performance due to implementation in C, making it much faster than Python lists for numerical tasks.

In short: NumPy is the backbone of scientific computing in Python.

In [5]:
import numpy as np # IMPORTING NumPy

In [14]:
np.__version__

'1.26.4'

# 1) ARRAY CREATION FUNCTIONS

In [19]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [21]:
type(my_list)

list

### Convert List to Array 

In [24]:
my_list

[0, 1, 2, 3, 4, 5]

In [26]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [28]:
print(type(arr))

<class 'numpy.ndarray'>


## Difference between List & Array

| Feature            | List                                                                 | NumPy Array                                                                 |
|--------------------|----------------------------------------------------------------------|------------------------------------------------------------------------------|
| **Type of Elements** | Can store heterogeneous types (different data types)                | Can only store homogeneous types (same data type)                           |
| **Performance**     | Slower for large data, especially in numerical operations           | Optimized for performance, faster for large numerical datasets              |
| **Memory Efficiency**| Less memory efficient for large datasets                            | More memory efficient for large datasets                                    |
| **Operations**      | Cannot perform vectorized operations directly                        | Supports vectorized operations (faster element-wise calculations)           |
| **Use Case**        | General-purpose collection                                           | Scientific computing, numerical computations, large datasets                |
| **Methods/Functions**| Built-in Python methods (e.g., `.append()`, `.extend()`, `.remove()`) | A vast set of numerical operations like `np.add()`, `np.mean()`, `np.dot()` |


### Zeros & Ones Arrays 

#### Zeros Array

A Zeros Array is an array where all elements are 0, created using numpy.zeros().  

Important Points:  

+ Syntax: np.zeros(shape, dtype=float)  
+ Default dtype is float.  
+ Commonly used to initialize arrays before filling them with values.  
+ Shape can be 1D, 2D, or multi-dimensional.  

EXAMPLE :  
import numpy as np  
zeros_arr = np.zeros((2, 3))  
print(zeros_arr)  
Output:  
[[0. 0. 0.]  
 [0. 0. 0.]  ]

In [37]:
np.zeros(5) #Parameter tunning

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros(5, dtype=int) #Hyperparameter tunning

array([0, 0, 0, 0, 0])

In [41]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [43]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.zeros([2,10])

### 2 -- always be rows  
### 10 -- always be column 

#### Ones Array

A Ones Array is an array where all elements are 1, created using numpy.ones().  

Important Points:  

+ Syntax: np.ones(shape, dtype=float)  
+ Default dtype is float.  
+ Useful for placeholders or mathematical operations where a base value of 1 is needed.  
+ Shape can be 1D, 2D, or multi-dimensional.  

Example:  
ones_arr = np.ones((2, 3))  
print(ones_arr)  
Output:  
[[1. 1. 1.]  
[1. 1. 1.]]  


In [64]:
np.ones(2)

array([1., 1.])

In [66]:
np.ones(2, dtype=int)

array([1, 1])

In [68]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Arange Function

np.arange() creates an array with evenly spaced values within a given range, similar to Python’s built-in range(), but returns a NumPy array instead of a list.

**numpy.arange(start, stop, step, dtype=None)**  

Parameters:   

+ start (optional) → Starting value (default: 0).  
+ stop (required) → End value (not included).  
+ step (optional) → Interval between values (default: 1).  
+ dtype (optional) → Data type of the output array.  

In [7]:
import numpy as np

In [11]:
# Basic usage
arr1 = np.arange(5)
print(arr1)

[0 1 2 3 4]


In [13]:
# With start and stop
arr2 = np.arange(2, 10)
print(arr2) 

[2 3 4 5 6 7 8 9]


In [15]:
# With step
arr3 = np.arange(2, 10, 2)
print(arr3)  

[2 4 6 8]


In [17]:
# With float step
arr4 = np.arange(0, 1, 0.2)
print(arr4) 

[0.  0.2 0.4 0.6 0.8]


In [19]:
np.arange(20,10) # 1st Arg < 2nd Arg

array([], dtype=int32)

In [21]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

### Random Values

NumPy’s random module allows us to generate random numbers for simulations, testing, and data science tasks.

Important Points:  

+ Use seed() to get the same random results every time (important in experiments).  
+ Random values are useful in machine learning, simulations, data augmentation, etc.  
+ rand() → 0 to 1, uniform distribution.  
+ randn() → normal distribution (bell curve).  

| Function              | Description                                                                   | Example                                       |
| --------------------- | ----------------------------------------------------------------------------- | --------------------------------------------- |
| `np.random.rand()`    | Generates random floats between **0 and 1** (uniform distribution)            | `np.random.rand(3)` → `[0.54 0.72 0.14]`      |
| `np.random.randn()`   | Generates random floats from **standard normal distribution** (mean=0, std=1) | `np.random.randn(3)` → `[0.12 -1.45 0.67]`    |
| `np.random.randint()` | Generates random integers in a given range                                    | `np.random.randint(1, 10, 5)` → `[3 8 6 1 4]` |
| `np.random.random()`  | Similar to `rand()` but takes shape as a tuple                                | `np.random.random((2,3))`                     |
| `np.random.choice()`  | Picks random elements from a given array                                      | `np.random.choice([1, 2, 3], 2)` → `[2 1]`    |
| `np.random.seed()`    | Sets the random seed for reproducibility                                      | `np.random.seed(42)`                          |


In [36]:
np.random.rand(3,2) #  Creates a 3 rows × 2 columns array of random floats between 0 and 1

array([[0.89615168, 0.6220608 ],
       [0.23429748, 0.50514688],
       [0.91737245, 0.81726347]])

In [42]:
np.random.rand(3) #  Creates a 1D array of 3 random floats between 0 and 1  

# Shape = 1D
# Length = 3
# Range = [0, 1)

array([0.21659029, 0.37936707, 0.64558086])

In [46]:
np.random.randint(4,6)  # returns a random integer 4 or 5 (6 is excluded)

5

In [52]:
np.random.randint(0,10) # returns a random integer from 0 to 9 (10 is excluded)

9

In [54]:
np.random.randint(0,10,4) # Generate 4 random number

array([6, 7, 4, 6])

In [58]:
np.random.randint(0,10,5) # Generate 5 random number

array([3, 8, 1, 9, 8])

In [13]:
n = np.random.randint(10,40,(8,10))
# 8 rows and 10 coloumns with random number between 10 to 40

In [15]:
n

array([[11, 32, 13, 21, 16, 20, 37, 29, 15, 10],
       [25, 28, 29, 22, 16, 28, 31, 12, 20, 15],
       [28, 37, 15, 19, 22, 17, 34, 17, 19, 27],
       [13, 35, 37, 35, 22, 18, 17, 23, 29, 36],
       [12, 12, 29, 11, 11, 34, 37, 21, 29, 31],
       [29, 27, 15, 34, 26, 25, 12, 35, 30, 28],
       [32, 31, 36, 28, 20, 36, 27, 30, 32, 30],
       [12, 20, 34, 23, 30, 16, 12, 17, 29, 23]])

## 2) ARRAY MANIPULATION FUNTION

Array manipulation in NumPy means reshaping, joining, splitting, or changing the arrangement of array elements without changing the actual data.

#### Reshaping – Change the shape of an array.

In [91]:
np.arange(1,13).reshape(3,4) # print no. in 3x4 rowns and column 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [95]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [97]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [99]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [107]:
arr = np.arange(1, 13).reshape(3, 4)  # create 3x4 array from 1 to 12
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Transpose
Flips an array over its diagonal, swapping rows with columns.

In [113]:
arr.T # transpose: swap rows and columns

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### Flattening
Converts a multi-dimensional array into a 1D array.

In [115]:
arr.flatten() # flatten: convert to 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 3) INDEXING & SLICING

In [27]:
mat = np.arange(0,100).reshape(10,10)

In [29]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
mat[5]  # element at index 5

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [45]:
mat[0:6] # elements from index 0 to 5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [33]:
mat[::-1]  # all elements in reverse order

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [35]:
mat[::2] # every 2nd element from start

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [39]:
mat[0]  # element at index 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
mat[0,5] # element at row 0, column 5 (2D array)

5

In [43]:
mat[5,-3] # element at row 5, 3rd column from end (2D array)

57

### : in matrix --- records  
### , in matrix --- specific position

In [48]:
# New 

In [50]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
row = 4
col = 5

In [54]:
col

5

In [56]:
row

4

In [58]:
mat[row,col]

45

In [60]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [62]:
# With Slices
mat[:,col] # HOW TO PRINT COLUMN INFOR

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [64]:
mat[col] # HOW TO PRINT ROWS

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [66]:
mat[:,-1] # LAST COLUMN

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [68]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## mat[4,:] ---> It will print 4th row
## mat[:,4] ---> It will print 4th column
## mat[4:] ---> It will print the rows from 4th till lat rows
## mat[:4] ---> print till 4th columns

In [73]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 --> It indicates only coulmn parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [75]:
mat[1:2,2:4]

array([[12, 13]])

In [77]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

### MASKING

In [80]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [82]:
# Print no. less than 50 
mat < 50 

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [84]:
# for no. 

mat[mat < 50] # Less than 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [86]:
 mat[mat > 50] # More than 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [88]:
mat[mat >= 50] # Less than 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## 4) Array Operations

#### 1. Basic Arithmetic Operations  
These are element-wise operations performed between two arrays of the same shape.  

+  '+' → Adds elements of two arrays.  
+  '-' → Subtracts elements of one array from another.  
+  '*' → Multiplies elements of two arrays.  
+  '/' → Divides elements of one array by another.  

Important Points:  

+ Arrays must have the same shape, or broadcasting rules apply.  
+ Operations are much faster than Python lists due to NumPy's optimized C-based implementation.  

Operations:
+ result = arr1 + arr2   
+ result = arr1 - arr2   
+ result = arr1 * arr2   
+ result = arr1 / arr2   

**Example**

In [144]:
#Create two arrays  
arr1 = np.array([10, 20, 30])  
arr2 = np.array([1, 2, 3])  

In [146]:
# Basic Arithmetic Operations 

In [148]:
print("Addition:", arr1 + arr2)    # Element-wise addition 

Addition: [11 22 33]


In [150]:
print("Subtraction:", arr1 - arr2) # Element-wise subtraction

Subtraction: [ 9 18 27]


In [152]:
print("Multiplication:", arr1 * arr2) # Element-wise multiplication 

Multiplication: [10 40 90]


In [154]:
print("Division:", arr1 / arr2)    # Element-wise division 

Division: [10. 10. 10.]


#### 2. Element-wise Operations  

Apply a function to each element of the array individually.  
+ np.square(arr) → Squares each element.  
+ np.sqrt(arr) → Takes the square root of each element.  
+ np.exp(arr) → Calculates the exponential (e^x) for each element.  

Important Points:  

+ These operations are vectorized — no need for loops.  
+ Faster and more memory-efficient than Python loops.  

Operations:
+ result = np.square(arr)  
+ result = np.sqrt(arr)  
+ result = np.exp(arr)  

**Example**

In [166]:
# Create an array
arr = np.array([1, 4, 9])

In [168]:
# Element-wise operations
print("Square:", np.square(arr))  

Square: [ 1 16 81]


In [170]:
print("Square Root:", np.sqrt(arr))  

Square Root: [1. 2. 3.]


In [172]:
print("Exponential:", np.exp(arr))   

Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03]


#### 3. Dot Product
+ np.dot(arr1, arr2) → Performs matrix multiplication (or inner product for 1D arrays).  

Important Points:  

+ Used in linear algebra, machine learning (e.g., weights × inputs), and graphics transformations.  
+ Shape compatibility is important: (m×n) dot (n×p) → (m×p)  

**Example**

In [184]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [186]:
# Dot product
dot_product = np.dot(arr1, arr2)

print("Dot Product:", dot_product)  # (1*4) + (2*5) + (3*6) = 32

Dot Product: 32


## 5) Statistical Operation

Statistical operations in NumPy help analyze data by finding measures like mean, median, standard deviation, and aggregate values like sum, min, and max.  

Important Points:  

+ Mean (np.mean) → Average value of array elements.  
+ Median (np.median) → Middle value after sorting the array.  
+ Standard Deviation (np.std) → Measures data spread from the mean.  
+ Sum (np.sum) → Adds all array elements.  
+ Min & Max (np.min, np.max) → Find smallest and largest values.  

**Example**

In [191]:
arr = np.array([10, 20, 30, 40, 50])

In [207]:
print("Mean:", np.mean(arr))  
# Mean: (sum of all elements) / (number of elements)

Mean: 30.0


In [209]:
print("Median:", np.median(arr))
# Median: Middle value after sorting (or avg of two middle values if even count)

Median: 30.0


In [211]:
print("Std Dev:", np.std(arr))    
# Standard Deviation: sqrt( sum( (x - mean)^2 ) / n )

Std Dev: 14.142135623730951


In [213]:
print("Sum:", np.sum(arr))  
# Sum: total of all elements

Sum: 150


In [215]:
print("Min:", np.min(arr))      
# Min: smallest value in array

Min: 10


In [217]:
print("Max:", np.max(arr))      
# Max: largest value in array

Max: 50


## 6) Logical Operations

Logical operations return boolean results (True/False) for each element based on a condition.  

Important Points:   

+ Used for filtering and conditional selection in arrays.  
+ Supports comparisons (>, <, ==, !=) and logical functions (np.logical_and, np.logical_or).  

**Example**

In [222]:
arr = np.array([1, 4, 7, 2, 5])

In [232]:
# Condition: elements greater than 3
bool_arr = arr > 3
print("Boolean Array:", bool_arr)   
# Boolean condition: arr > value → True if element satisfies, else False

Boolean Array: [False  True  True False  True]


In [228]:
# Extracting values greater than 3
print("Filtered Values:", arr[bool_arr])  

Filtered Values: [4 7 5]


In [230]:
# Boolean condition: arr > value → True if element satisfies, else False
# Logical AND: np.logical_and(cond1, cond2)
# Logical OR: np.logical_or(cond1, cond2)
# Usage: arr[condition] → returns filtered elements

## 7) Broadcasting

The ability of NumPy to perform arithmetic operations between arrays of different shapes by automatically expanding the smaller array to match the larger one.

Important Points:

+ Saves time — no need for explicit loops.
+ Works only if dimensions are compatible.
+ Scalars (single values) can be broadcast to all elements.

In [7]:
arr = np.array([1, 2, 3])
result = arr + 5  # Adds 5 to each element
print(result)  # [6 7 8]

[6 7 8]


In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = arr2 + scalar
print(result)

[[11 12 13]
 [14 15 16]]


## 8) Concatenation

Joining two or more arrays along a specified axis.

Important Points:

+ axis=0 → stack rows (vertical).
+ axis=1 → stack columns (horizontal).
+ Arrays must have the same shape except in the concatenation axis.

In [18]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 9) Stacking

Combining arrays into a new dimension (vertical or horizontal).

Important Points:

+ np.vstack() → vertical stack.
+ np.hstack() → horizontal stack.
+ Similar to concatenation but easier to read.

In [27]:
# vertical stack
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
stacked = np.vstack((arr1, arr2))
print(stacked)

[[1 2]
 [3 4]]


In [29]:
# horizontal stack.
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
stacked = np.hstack((arr1, arr2))
print(stacked)

[1 2 3 4]


## 10) Linear Algebra

Mathematical operations on matrices such as finding eigenvalues and eigenvectors.

Important Points:

+ np.linalg.eig() → returns eigenvalues and eigenvectors.
+ Useful in machine learning, PCA, and transformations.


In [34]:
matrix = np.array([[2, 0], [0, 3]])
values, vectors = np.linalg.eig(matrix)
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


## 11) Random Sampling

Selecting random elements from an array.

Important Points:

+ replace=True → allows repetition.
+ replace=False → no repetition.
+ Useful for simulations and testing.

In [39]:
arr = np.array([10, 20, 30, 40, 50])
sample = np.random.choice(arr, size=3, replace=False)
print(sample)

[50 20 40]


## 12) Avoiding Copy`

Create an independent copy of an array to avoid unintentional changes.

Important Points:

+ Without .copy(), modifying one array may affect the original.
+ Always use .copy() when you want a safe duplicate.

In [48]:
arr = np.array([1, 2, 3])
new_arr = arr.copy()
new_arr[0] = 100
print(arr)      # Original unchanged
print(new_arr)  # Modified copy

[1 2 3]
[100   2   3]


## 13) Handling NaN

Detecting and working with missing or invalid numerical values (NaN).

Important Points:

+ np.isnan() → detects NaNs.
+ .any() checks if any element is NaN.



In [59]:
arr = np.array([1, np.nan, 3])
has_nan = np.isnan(arr).any()
print("Contains NaN? :", has_nan)

Contains NaN? : True


## 14) Vectorized Operations


Performing operations on entire arrays without using loops.



Important Points:

+ Faster than Python loops.
+ Takes advantage of NumPy’s optimized C backend.

In [64]:
arr = np.array([0, np.pi/2, np.pi])
result = np.sin(arr)
print(result)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## 15) Save and Load

Saving arrays to disk and loading them later.

Important Points:

+ .npy format is NumPy’s native binary storage.
+ Preserves data type and shape.

In [69]:
arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 2 3]


## 16) Memory Usage

Checking how much memory an array consumes.


Important Points:

+ .nbytes gives total memory in bytes.
+ Memory depends on shape × element size.

In [ ]:
Example:

arr = np.array([1, 2, 3], dtype=np.int32)
print("Memory used:", arr.nbytes, "bytes")